/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorldSkillsIndexRouteImport } from './routes/worldSkills/index'
import { Route as StudentLiveIndexRouteImport } from './routes/studentLive/index'
import { Route as ScholarshipIndexRouteImport } from './routes/scholarship/index'
import { Route as ScheduleIndexRouteImport } from './routes/schedule/index'
import { Route as PracticeIndexRouteImport } from './routes/practice/index'
import { Route as OurGraduatesIndexRouteImport } from './routes/ourGraduates/index'
import { Route as OrdersIndexRouteImport } from './routes/orders/index'
import { Route as NewsIndexRouteImport } from './routes/news/index'
import { Route as MediaIndexRouteImport } from './routes/media/index'
import { Route as LicenseIndexRouteImport } from './routes/license/index'
import { Route as GraduatesReviewsIndexRouteImport } from './routes/graduatesReviews/index'
import { Route as ExamInfoIndexRouteImport } from './routes/examInfo/index'
import { Route as EmploymentIndexRouteImport } from './routes/employment/index'
import { Route as DualEducationIndexRouteImport } from './routes/dualEducation/index'
import { Route as DocumentsIndexRouteImport } from './routes/documents/index'
import { Route as CounteringCorruptionIndexRouteImport } from './routes/counteringCorruption/index'
import { Route as CorrespondenceIndexRouteImport } from './routes/correspondence/index'
import { Route as ContestResultsIndexRouteImport } from './routes/contestResults/index'
import { Route as CompanyReviewsIndexRouteImport } from './routes/companyReviews/index'
import { Route as CollegeHistoryIndexRouteImport } from './routes/collegeHistory/index'
import { Route as CharterIndexRouteImport } from './routes/charter/index'
import { Route as AlumniAssociationIndexRouteImport } from './routes/alumniAssociation/index'
import { Route as AdmissionRulesIndexRouteImport } from './routes/admissionRules/index'
import { Route as TeachingStaffIndexRouteImport } from './routes/TeachingStaff/index'
import { Route as SymbolsIndexRouteImport } from './routes/Symbols/index'
import { Route as SpecialsIndexRouteImport } from './routes/Specials/index'
import { Route as DormitoryIndexRouteImport } from './routes/Dormitory/index'
import { Route as ContactsIndexRouteImport } from './routes/Contacts/index'
import { Route as CollegeManagementIndexRouteImport } from './routes/CollegeManagement/index'
import { Route as NewsNewsIdRouteImport } from './routes/news/$newsId'
import { Route as NotFoundPageNotFoundPageRouteImport } from './routes/NotFoundPage/NotFoundPage'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldSkillsIndexRoute = WorldSkillsIndexRouteImport.update({
  id: '/worldSkills/',
  path: '/worldSkills/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentLiveIndexRoute = StudentLiveIndexRouteImport.update({
  id: '/studentLive/',
  path: '/studentLive/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScholarshipIndexRoute = ScholarshipIndexRouteImport.update({
  id: '/scholarship/',
  path: '/scholarship/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleIndexRoute = ScheduleIndexRouteImport.update({
  id: '/schedule/',
  path: '/schedule/',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeIndexRoute = PracticeIndexRouteImport.update({
  id: '/practice/',
  path: '/practice/',
  getParentRoute: () => rootRouteImport,
} as any)
const OurGraduatesIndexRoute = OurGraduatesIndexRouteImport.update({
  id: '/ourGraduates/',
  path: '/ourGraduates/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaIndexRoute = MediaIndexRouteImport.update({
  id: '/media/',
  path: '/media/',
  getParentRoute: () => rootRouteImport,
} as any)
const LicenseIndexRoute = LicenseIndexRouteImport.update({
  id: '/license/',
  path: '/license/',
  getParentRoute: () => rootRouteImport,
} as any)
const GraduatesReviewsIndexRoute = GraduatesReviewsIndexRouteImport.update({
  id: '/graduatesReviews/',
  path: '/graduatesReviews/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamInfoIndexRoute = ExamInfoIndexRouteImport.update({
  id: '/examInfo/',
  path: '/examInfo/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmploymentIndexRoute = EmploymentIndexRouteImport.update({
  id: '/employment/',
  path: '/employment/',
  getParentRoute: () => rootRouteImport,
} as any)
const DualEducationIndexRoute = DualEducationIndexRouteImport.update({
  id: '/dualEducation/',
  path: '/dualEducation/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsIndexRoute = DocumentsIndexRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => rootRouteImport,
} as any)
const CounteringCorruptionIndexRoute =
  CounteringCorruptionIndexRouteImport.update({
    id: '/counteringCorruption/',
    path: '/counteringCorruption/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CorrespondenceIndexRoute = CorrespondenceIndexRouteImport.update({
  id: '/correspondence/',
  path: '/correspondence/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContestResultsIndexRoute = ContestResultsIndexRouteImport.update({
  id: '/contestResults/',
  path: '/contestResults/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyReviewsIndexRoute = CompanyReviewsIndexRouteImport.update({
  id: '/companyReviews/',
  path: '/companyReviews/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollegeHistoryIndexRoute = CollegeHistoryIndexRouteImport.update({
  id: '/collegeHistory/',
  path: '/collegeHistory/',
  getParentRoute: () => rootRouteImport,
} as any)
const CharterIndexRoute = CharterIndexRouteImport.update({
  id: '/charter/',
  path: '/charter/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlumniAssociationIndexRoute = AlumniAssociationIndexRouteImport.update({
  id: '/alumniAssociation/',
  path: '/alumniAssociation/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionRulesIndexRoute = AdmissionRulesIndexRouteImport.update({
  id: '/admissionRules/',
  path: '/admissionRules/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachingStaffIndexRoute = TeachingStaffIndexRouteImport.update({
  id: '/TeachingStaff/',
  path: '/TeachingStaff/',
  getParentRoute: () => rootRouteImport,
} as any)
const SymbolsIndexRoute = SymbolsIndexRouteImport.update({
  id: '/Symbols/',
  path: '/Symbols/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialsIndexRoute = SpecialsIndexRouteImport.update({
  id: '/Specials/',
  path: '/Specials/',
  getParentRoute: () => rootRouteImport,
} as any)
const DormitoryIndexRoute = DormitoryIndexRouteImport.update({
  id: '/Dormitory/',
  path: '/Dormitory/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsIndexRoute = ContactsIndexRouteImport.update({
  id: '/Contacts/',
  path: '/Contacts/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollegeManagementIndexRoute = CollegeManagementIndexRouteImport.update({
  id: '/CollegeManagement/',
  path: '/CollegeManagement/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsNewsIdRoute = NewsNewsIdRouteImport.update({
  id: '/news/$newsId',
  path: '/news/$newsId',
  getParentRoute: () => rootRouteImport,
} as any)
const NotFoundPageNotFoundPageRoute =
  NotFoundPageNotFoundPageRouteImport.update({
    id: '/NotFoundPage/NotFoundPage',
    path: '/NotFoundPage/NotFoundPage',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/NotFoundPage/NotFoundPage': typeof NotFoundPageNotFoundPageRoute
  '/news/$newsId': typeof NewsNewsIdRoute
  '/CollegeManagement': typeof CollegeManagementIndexRoute
  '/Contacts': typeof ContactsIndexRoute
  '/Dormitory': typeof DormitoryIndexRoute
  '/Specials': typeof SpecialsIndexRoute
  '/Symbols': typeof SymbolsIndexRoute
  '/TeachingStaff': typeof TeachingStaffIndexRoute
  '/admissionRules': typeof AdmissionRulesIndexRoute
  '/alumniAssociation': typeof AlumniAssociationIndexRoute
  '/charter': typeof CharterIndexRoute
  '/collegeHistory': typeof CollegeHistoryIndexRoute
  '/companyReviews': typeof CompanyReviewsIndexRoute
  '/contestResults': typeof ContestResultsIndexRoute
  '/correspondence': typeof CorrespondenceIndexRoute
  '/counteringCorruption': typeof CounteringCorruptionIndexRoute
  '/documents': typeof DocumentsIndexRoute
  '/dualEducation': typeof DualEducationIndexRoute
  '/employment': typeof EmploymentIndexRoute
  '/examInfo': typeof ExamInfoIndexRoute
  '/graduatesReviews': typeof GraduatesReviewsIndexRoute
  '/license': typeof LicenseIndexRoute
  '/media': typeof MediaIndexRoute
  '/news': typeof NewsIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/ourGraduates': typeof OurGraduatesIndexRoute
  '/practice': typeof PracticeIndexRoute
  '/schedule': typeof ScheduleIndexRoute
  '/scholarship': typeof ScholarshipIndexRoute
  '/studentLive': typeof StudentLiveIndexRoute
  '/worldSkills': typeof WorldSkillsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/NotFoundPage/NotFoundPage': typeof NotFoundPageNotFoundPageRoute
  '/news/$newsId': typeof NewsNewsIdRoute
  '/CollegeManagement': typeof CollegeManagementIndexRoute
  '/Contacts': typeof ContactsIndexRoute
  '/Dormitory': typeof DormitoryIndexRoute
  '/Specials': typeof SpecialsIndexRoute
  '/Symbols': typeof SymbolsIndexRoute
  '/TeachingStaff': typeof TeachingStaffIndexRoute
  '/admissionRules': typeof AdmissionRulesIndexRoute
  '/alumniAssociation': typeof AlumniAssociationIndexRoute
  '/charter': typeof CharterIndexRoute
  '/collegeHistory': typeof CollegeHistoryIndexRoute
  '/companyReviews': typeof CompanyReviewsIndexRoute
  '/contestResults': typeof ContestResultsIndexRoute
  '/correspondence': typeof CorrespondenceIndexRoute
  '/counteringCorruption': typeof CounteringCorruptionIndexRoute
  '/documents': typeof DocumentsIndexRoute
  '/dualEducation': typeof DualEducationIndexRoute
  '/employment': typeof EmploymentIndexRoute
  '/examInfo': typeof ExamInfoIndexRoute
  '/graduatesReviews': typeof GraduatesReviewsIndexRoute
  '/license': typeof LicenseIndexRoute
  '/media': typeof MediaIndexRoute
  '/news': typeof NewsIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/ourGraduates': typeof OurGraduatesIndexRoute
  '/practice': typeof PracticeIndexRoute
  '/schedule': typeof ScheduleIndexRoute
  '/scholarship': typeof ScholarshipIndexRoute
  '/studentLive': typeof StudentLiveIndexRoute
  '/worldSkills': typeof WorldSkillsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/NotFoundPage/NotFoundPage': typeof NotFoundPageNotFoundPageRoute
  '/news/$newsId': typeof NewsNewsIdRoute
  '/CollegeManagement/': typeof CollegeManagementIndexRoute
  '/Contacts/': typeof ContactsIndexRoute
  '/Dormitory/': typeof DormitoryIndexRoute
  '/Specials/': typeof SpecialsIndexRoute
  '/Symbols/': typeof SymbolsIndexRoute
  '/TeachingStaff/': typeof TeachingStaffIndexRoute
  '/admissionRules/': typeof AdmissionRulesIndexRoute
  '/alumniAssociation/': typeof AlumniAssociationIndexRoute
  '/charter/': typeof CharterIndexRoute
  '/collegeHistory/': typeof CollegeHistoryIndexRoute
  '/companyReviews/': typeof CompanyReviewsIndexRoute
  '/contestResults/': typeof ContestResultsIndexRoute
  '/correspondence/': typeof CorrespondenceIndexRoute
  '/counteringCorruption/': typeof CounteringCorruptionIndexRoute
  '/documents/': typeof DocumentsIndexRoute
  '/dualEducation/': typeof DualEducationIndexRoute
  '/employment/': typeof EmploymentIndexRoute
  '/examInfo/': typeof ExamInfoIndexRoute
  '/graduatesReviews/': typeof GraduatesReviewsIndexRoute
  '/license/': typeof LicenseIndexRoute
  '/media/': typeof MediaIndexRoute
  '/news/': typeof NewsIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/ourGraduates/': typeof OurGraduatesIndexRoute
  '/practice/': typeof PracticeIndexRoute
  '/schedule/': typeof ScheduleIndexRoute
  '/scholarship/': typeof ScholarshipIndexRoute
  '/studentLive/': typeof StudentLiveIndexRoute
  '/worldSkills/': typeof WorldSkillsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/NotFoundPage/NotFoundPage'
    | '/news/$newsId'
    | '/CollegeManagement'
    | '/Contacts'
    | '/Dormitory'
    | '/Specials'
    | '/Symbols'
    | '/TeachingStaff'
    | '/admissionRules'
    | '/alumniAssociation'
    | '/charter'
    | '/collegeHistory'
    | '/companyReviews'
    | '/contestResults'
    | '/correspondence'
    | '/counteringCorruption'
    | '/documents'
    | '/dualEducation'
    | '/employment'
    | '/examInfo'
    | '/graduatesReviews'
    | '/license'
    | '/media'
    | '/news'
    | '/orders'
    | '/ourGraduates'
    | '/practice'
    | '/schedule'
    | '/scholarship'
    | '/studentLive'
    | '/worldSkills'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/NotFoundPage/NotFoundPage'
    | '/news/$newsId'
    | '/CollegeManagement'
    | '/Contacts'
    | '/Dormitory'
    | '/Specials'
    | '/Symbols'
    | '/TeachingStaff'
    | '/admissionRules'
    | '/alumniAssociation'
    | '/charter'
    | '/collegeHistory'
    | '/companyReviews'
    | '/contestResults'
    | '/correspondence'
    | '/counteringCorruption'
    | '/documents'
    | '/dualEducation'
    | '/employment'
    | '/examInfo'
    | '/graduatesReviews'
    | '/license'
    | '/media'
    | '/news'
    | '/orders'
    | '/ourGraduates'
    | '/practice'
    | '/schedule'
    | '/scholarship'
    | '/studentLive'
    | '/worldSkills'
  id:
    | '__root__'
    | '/'
    | '/NotFoundPage/NotFoundPage'
    | '/news/$newsId'
    | '/CollegeManagement/'
    | '/Contacts/'
    | '/Dormitory/'
    | '/Specials/'
    | '/Symbols/'
    | '/TeachingStaff/'
    | '/admissionRules/'
    | '/alumniAssociation/'
    | '/charter/'
    | '/collegeHistory/'
    | '/companyReviews/'
    | '/contestResults/'
    | '/correspondence/'
    | '/counteringCorruption/'
    | '/documents/'
    | '/dualEducation/'
    | '/employment/'
    | '/examInfo/'
    | '/graduatesReviews/'
    | '/license/'
    | '/media/'
    | '/news/'
    | '/orders/'
    | '/ourGraduates/'
    | '/practice/'
    | '/schedule/'
    | '/scholarship/'
    | '/studentLive/'
    | '/worldSkills/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NotFoundPageNotFoundPageRoute: typeof NotFoundPageNotFoundPageRoute
  NewsNewsIdRoute: typeof NewsNewsIdRoute
  CollegeManagementIndexRoute: typeof CollegeManagementIndexRoute
  ContactsIndexRoute: typeof ContactsIndexRoute
  DormitoryIndexRoute: typeof DormitoryIndexRoute
  SpecialsIndexRoute: typeof SpecialsIndexRoute
  SymbolsIndexRoute: typeof SymbolsIndexRoute
  TeachingStaffIndexRoute: typeof TeachingStaffIndexRoute
  AdmissionRulesIndexRoute: typeof AdmissionRulesIndexRoute
  AlumniAssociationIndexRoute: typeof AlumniAssociationIndexRoute
  CharterIndexRoute: typeof CharterIndexRoute
  CollegeHistoryIndexRoute: typeof CollegeHistoryIndexRoute
  CompanyReviewsIndexRoute: typeof CompanyReviewsIndexRoute
  ContestResultsIndexRoute: typeof ContestResultsIndexRoute
  CorrespondenceIndexRoute: typeof CorrespondenceIndexRoute
  CounteringCorruptionIndexRoute: typeof CounteringCorruptionIndexRoute
  DocumentsIndexRoute: typeof DocumentsIndexRoute
  DualEducationIndexRoute: typeof DualEducationIndexRoute
  EmploymentIndexRoute: typeof EmploymentIndexRoute
  ExamInfoIndexRoute: typeof ExamInfoIndexRoute
  GraduatesReviewsIndexRoute: typeof GraduatesReviewsIndexRoute
  LicenseIndexRoute: typeof LicenseIndexRoute
  MediaIndexRoute: typeof MediaIndexRoute
  NewsIndexRoute: typeof NewsIndexRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  OurGraduatesIndexRoute: typeof OurGraduatesIndexRoute
  PracticeIndexRoute: typeof PracticeIndexRoute
  ScheduleIndexRoute: typeof ScheduleIndexRoute
  ScholarshipIndexRoute: typeof ScholarshipIndexRoute
  StudentLiveIndexRoute: typeof StudentLiveIndexRoute
  WorldSkillsIndexRoute: typeof WorldSkillsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worldSkills/': {
      id: '/worldSkills/'
      path: '/worldSkills'
      fullPath: '/worldSkills'
      preLoaderRoute: typeof WorldSkillsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studentLive/': {
      id: '/studentLive/'
      path: '/studentLive'
      fullPath: '/studentLive'
      preLoaderRoute: typeof StudentLiveIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scholarship/': {
      id: '/scholarship/'
      path: '/scholarship'
      fullPath: '/scholarship'
      preLoaderRoute: typeof ScholarshipIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule/': {
      id: '/schedule/'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/': {
      id: '/practice/'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ourGraduates/': {
      id: '/ourGraduates/'
      path: '/ourGraduates'
      fullPath: '/ourGraduates'
      preLoaderRoute: typeof OurGraduatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/': {
      id: '/media/'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/license/': {
      id: '/license/'
      path: '/license'
      fullPath: '/license'
      preLoaderRoute: typeof LicenseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graduatesReviews/': {
      id: '/graduatesReviews/'
      path: '/graduatesReviews'
      fullPath: '/graduatesReviews'
      preLoaderRoute: typeof GraduatesReviewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examInfo/': {
      id: '/examInfo/'
      path: '/examInfo'
      fullPath: '/examInfo'
      preLoaderRoute: typeof ExamInfoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employment/': {
      id: '/employment/'
      path: '/employment'
      fullPath: '/employment'
      preLoaderRoute: typeof EmploymentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dualEducation/': {
      id: '/dualEducation/'
      path: '/dualEducation'
      fullPath: '/dualEducation'
      preLoaderRoute: typeof DualEducationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/': {
      id: '/documents/'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/counteringCorruption/': {
      id: '/counteringCorruption/'
      path: '/counteringCorruption'
      fullPath: '/counteringCorruption'
      preLoaderRoute: typeof CounteringCorruptionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/correspondence/': {
      id: '/correspondence/'
      path: '/correspondence'
      fullPath: '/correspondence'
      preLoaderRoute: typeof CorrespondenceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contestResults/': {
      id: '/contestResults/'
      path: '/contestResults'
      fullPath: '/contestResults'
      preLoaderRoute: typeof ContestResultsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companyReviews/': {
      id: '/companyReviews/'
      path: '/companyReviews'
      fullPath: '/companyReviews'
      preLoaderRoute: typeof CompanyReviewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collegeHistory/': {
      id: '/collegeHistory/'
      path: '/collegeHistory'
      fullPath: '/collegeHistory'
      preLoaderRoute: typeof CollegeHistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charter/': {
      id: '/charter/'
      path: '/charter'
      fullPath: '/charter'
      preLoaderRoute: typeof CharterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alumniAssociation/': {
      id: '/alumniAssociation/'
      path: '/alumniAssociation'
      fullPath: '/alumniAssociation'
      preLoaderRoute: typeof AlumniAssociationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissionRules/': {
      id: '/admissionRules/'
      path: '/admissionRules'
      fullPath: '/admissionRules'
      preLoaderRoute: typeof AdmissionRulesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/TeachingStaff/': {
      id: '/TeachingStaff/'
      path: '/TeachingStaff'
      fullPath: '/TeachingStaff'
      preLoaderRoute: typeof TeachingStaffIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Symbols/': {
      id: '/Symbols/'
      path: '/Symbols'
      fullPath: '/Symbols'
      preLoaderRoute: typeof SymbolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Specials/': {
      id: '/Specials/'
      path: '/Specials'
      fullPath: '/Specials'
      preLoaderRoute: typeof SpecialsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Dormitory/': {
      id: '/Dormitory/'
      path: '/Dormitory'
      fullPath: '/Dormitory'
      preLoaderRoute: typeof DormitoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Contacts/': {
      id: '/Contacts/'
      path: '/Contacts'
      fullPath: '/Contacts'
      preLoaderRoute: typeof ContactsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/CollegeManagement/': {
      id: '/CollegeManagement/'
      path: '/CollegeManagement'
      fullPath: '/CollegeManagement'
      preLoaderRoute: typeof CollegeManagementIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$newsId': {
      id: '/news/$newsId'
      path: '/news/$newsId'
      fullPath: '/news/$newsId'
      preLoaderRoute: typeof NewsNewsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/NotFoundPage/NotFoundPage': {
      id: '/NotFoundPage/NotFoundPage'
      path: '/NotFoundPage/NotFoundPage'
      fullPath: '/NotFoundPage/NotFoundPage'
      preLoaderRoute: typeof NotFoundPageNotFoundPageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NotFoundPageNotFoundPageRoute: NotFoundPageNotFoundPageRoute,
  NewsNewsIdRoute: NewsNewsIdRoute,
  CollegeManagementIndexRoute: CollegeManagementIndexRoute,
  ContactsIndexRoute: ContactsIndexRoute,
  DormitoryIndexRoute: DormitoryIndexRoute,
  SpecialsIndexRoute: SpecialsIndexRoute,
  SymbolsIndexRoute: SymbolsIndexRoute,
  TeachingStaffIndexRoute: TeachingStaffIndexRoute,
  AdmissionRulesIndexRoute: AdmissionRulesIndexRoute,
  AlumniAssociationIndexRoute: AlumniAssociationIndexRoute,
  CharterIndexRoute: CharterIndexRoute,
  CollegeHistoryIndexRoute: CollegeHistoryIndexRoute,
  CompanyReviewsIndexRoute: CompanyReviewsIndexRoute,
  ContestResultsIndexRoute: ContestResultsIndexRoute,
  CorrespondenceIndexRoute: CorrespondenceIndexRoute,
  CounteringCorruptionIndexRoute: CounteringCorruptionIndexRoute,
  DocumentsIndexRoute: DocumentsIndexRoute,
  DualEducationIndexRoute: DualEducationIndexRoute,
  EmploymentIndexRoute: EmploymentIndexRoute,
  ExamInfoIndexRoute: ExamInfoIndexRoute,
  GraduatesReviewsIndexRoute: GraduatesReviewsIndexRoute,
  LicenseIndexRoute: LicenseIndexRoute,
  MediaIndexRoute: MediaIndexRoute,
  NewsIndexRoute: NewsIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  OurGraduatesIndexRoute: OurGraduatesIndexRoute,
  PracticeIndexRoute: PracticeIndexRoute,
  ScheduleIndexRoute: ScheduleIndexRoute,
  ScholarshipIndexRoute: ScholarshipIndexRoute,
  StudentLiveIndexRoute: StudentLiveIndexRoute,
  WorldSkillsIndexRoute: WorldSkillsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
